### ISSUE TITLE
AttributeError: [E046] Can't retrieve unregistered extension attribute 'score'. Did you forget to call the `set_extension` method?

### ISSUE THREAD

**Issue by scherbakovdmitri** [BCHSI/social-determinants-of-health-clbp#2]
Hello, I have the following issue with CNN model (Hybrid model runs fine), can it be something with config file? 
Thank you! 
>>> for ent in doc.ents:
...     print(ent, ent.label_,ent._.score,ent._.cui, sep=" | ")
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/scherbak/Library/Python/3.9/lib/python/site-packages/spacy/tokens/underscore.py", line 47, in __getattr__
    raise AttributeError(Errors.E046.format(name=name))
AttributeError: [E046] Can't retrieve unregistered extension attribute 'score'. Did you forget to call the `set_extension` method?

**Comment by scherbakovdmitri** [comment]
I figured out that indeed score was not set for CNN model, and so the example code for CNN model is the same as for hybrid but without using the score:
```
import spacy
nlp = spacy.load("en_sdoh_cnn_ner_cui")
text = "Home Environment:  Lives with family  Work: disability"
doc = nlp(text)

for ent in doc.ents:
    print(ent, ent.label_, ent._.cui, sep=" | ")
```

**Comment by scherbakovdmitri** [comment]
closing the issue

**Comment by DSLituiev** [comment]
Good to hear it all resolved
